kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: greeting-console
spec:
  nodeSelector: {}
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: 'https://github.com/vincent9401/do400-greeting-console'
      ref: main
  output:
    to:
      kind: DockerImage
      name: quay.io/vincent9401/greeting-console
    pushSecret:
      name: vincent9401-auth.json
